---
name: Lint
"on":
  push:
  pull_request:

jobs:

  lint-yaml:
    name: Lint YAML files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.1.4
      - name: Install linter
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Lint
        run: |
          yamllint .

  check-secrets:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: '0'
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@v1.2.0