name: Run complete installation of dotfiles
on:
  push:
  pull_request:

jobs:

  tests:
    name: Test full installation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Run install
        run : |
          ./install.sh
