name: Run complete installation of dotfiles
on:
  push:
  pull_request:

jobs:

  lint:
    name: Test full installation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Run install
        run : |
          ./install.sh

  lint:
    name: Check updated copyrights
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Search and check copyright notice years
        run : |
          grep "$(date +'\-%Y')" ./LICENSE.md
