---
name: Tests
"on":
  push:
  pull_request:

jobs:

  tests:
    name: Run full installation
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@master
      - name: Run install
        run : ./install.sh
