---
name: Tests
"on":
  push:
  pull_request:
  schedule:
    # Run tests every Monday at 9:17 to catch regressions.
    - cron: "17 9 * * 1"

jobs:

  tests:
    name: Run full installation
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install Zsh
        run: |
          brew install zsh
      - name: Run install
        # GitHub macOS images forces bash as default:
        #   https://github.com/actions/virtual-environments/blob
        #   /0d93dd2fc97a0708d5f35ccda0e1be53c996630d/images/macos/provision
        #   /configuration/shell-change.sh#L3-L5
        run: |
          # Change default shell.
          sudo chsh -s /bin/zsh $USERNAME
          sudo chsh -s /bin/zsh root
          # Ask for the administrator password upfront.
          sudo -v
          # Keep-alive: update existing `sudo` time stamp until script has finished.
          while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
          zsh ./install.sh